name: pipeline

on:
  push:
    branches: [master]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          bash scripts/app_build.sh
      - name: Upload to S3 bucket
        uses: qoqa/action-s3-cp@v1.1
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: "ssm-label"
          AWS_S3_PATH: "/"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1"
          FILE: dist/*
